include(cmake/CPM.cmake)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/modules")

if(NOT CPM_USE_LOCAL_PACKAGES)
  set(CPM_USE_LOCAL_PACKAGES ON)
endif()


CPMAddPackage(
  URI "gh:InCom-0/woff2#otfccxx"
  OPTIONS "NOISY_LOGGING OFF" "BUILD_SHARED_LIBS OFF"
  FIND_PACKAGE_ARGUMENTS NAME WOFF2
)

CPMAddPackage(
  URI "gh:madler/zlib@1.3.1.2"
  OPTIONS
  "ZLIB_BUILD_SHARED OFF"
  "ZLIB_INSTALL OFF"
  "ZLIB_BUILD_TESTING OFF"
  NAME ZLIB
)


if(WOFF2_ADDED)
  set(OTS_WOFF2_BUILDFROMSOURCE TRUE)
endif()

if(ZLIB_ADDED)
  set(OTS_ZLIB_BUILDFROMSOURCE TRUE)
endif()
