include(cmake/CPM.cmake)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/modules")

if(NOT DEFINED CPM_USE_LOCAL_PACKAGES)
  set(CPM_USE_LOCAL_PACKAGES ON)
endif()


CPMAddPackage(
  URI "gh:InCom-0/woff2#otfccxx"
  OPTIONS "NOISY_LOGGING OFF" "BUILD_SHARED_LIBS OFF"
  FIND_PACKAGE_ARGUMENTS NAME WOFF2
)


if(woff2_ADDED)
  set(OTFCCXX_WOFF2_BUILDFROMSOURCE TRUE)
endif()